Style/LeadingCommentSpace:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

AllCops:
  Exclude:
    - 'config.ru'

# Disable metrics bellow once the library is cleaned up

AbcSize:
  Enabled: false
